from __future__ import annotations

import os
import warnings
from typing import Any, Dict, Optional

import numpy as np


# ---------------------------------------------------------------------------
# Touchstone Exporter / Importer
# ---------------------------------------------------------------------------


class TouchstoneExporter:
    """Export S-parameter data to Touchstone 1.x format files.

    Supports .s1p through .s4p formats with real/imaginary representation.

    Parameters
    ----------
    num_ports : int, optional
        Number of ports (1-4). Default 2.

    Example
    -------
    >>> exporter = TouchstoneExporter(num_ports=2)
    >>> freq = np.array([1e9, 2e9])
    >>> S = np.zeros((2, 2, 2), dtype=complex)
    >>> S[0, 0, 0] = 0.1 + 0.2j
    >>> exporter.export("test.s2p", freq, S)
    """

    def __init__(self, num_ports: int = 2) -> None:
        if not (1 <= num_ports <= 4):
            raise ValueError("num_ports must be between 1 and 4.")
        self.num_ports = num_ports

    def _validate_S_params(self, S_params: Any) -> bool:
        """Validate that *S_params* has shape (N_freq, N_ports, N_ports).

        Parameters
        ----------
        S_params : array-like
            S-parameters as a 3-D complex array.

        Returns
        -------
        bool
            ``True`` if valid.
        """
        arr = np.asarray(S_params)
        expected_shape = (arr.shape[0], self.num_ports, self.num_ports)
        if arr.ndim != 3:
            raise ValueError(
                f"S_params must be 3-D; got {arr.ndim}-D array with shape {arr.shape}."
            )
        if arr.shape[-2:] != (self.num_ports, self.num_ports):
            raise ValueError(
                f"Last two dims of S_params must be ({self.num_ports}, "
                f"{self.num_ports}); got {arr.shape[-2:]}."
            )
        return True

    def export(self, filename: str, frequency_Hz: np.ndarray, S_params: Any) -> None:
        """Write S-parameters to a Touchstone .sNp file.

        Parameters
        ----------
        filename : str
            Output file name (e.g. ``"data.s2p"``).
        frequency_Hz : np.ndarray
            Frequency vector in Hz.
        S_params : array-like
            Complex S-parameters of shape ``(N_freq, N_ports, N_ports)``.
        """
        self._validate_S_params(S_params)
        arr = np.asarray(S_params)
        freq_GHz = np.asarray(frequency_Hz) / 1e9

        n_freq = arr.shape[0]
        Np = self.num_ports

        # Build file content
        lines: list[str] = []
        lines.append(f"#! Touchstone {Np} port R 1 A")
        lines.append(f"! Generated by TouchstoneExporter")
        lines.append(f"# GHz R A f {freq_GHz[0]:.15e}")

        for i in range(n_freq):
            # Each data row: freq real1 imag1 real2 imag2 ...
            parts = [f"{freq_GHz[i]:.15e}"]
            for p in range(Np):
                for q in range(Np):
                    val = arr[i, p, q]
                    parts.append(f"{val.real:.15e}")
                    parts.append(f"{val.imag:.15e}")
            lines.append(" ".join(parts))

        content = "\n".join(lines) + "\n"

        with open(filename, "w") as fh:
            fh.write(content)


class TouchstoneImporter:
    """Parse Touchstone 1.x format files.

    Example
    -------
    >>> importer = TouchstoneImporter()
    >>> data = importer.import_file("test.s2p")
    >>> print(data["metadata"])
    """

    def __init__(self) -> None:
        self.num_ports: int = 2
        self.datatype: str = "R"
        self.format_version: str = "1.0"
        self.frequency_Hz: np.ndarray = np.array([], dtype=np.float64)

    def _parse_header(self, lines: list[str]) -> dict:
        """Parse the first few lines of a Touchstone file for metadata.

        Parameters
        ----------
        lines : list[str]
            Lines from the top of the file (including comments and data line).

        Returns
        -------
        dict
            Dictionary with keys ``format_version``, ``num_ports``, ``datatype``,
            ``frequency_unit`` (Hz or MHz), ``frequency_Hz``.
        """
        meta: dict[str, Any] = {
            "format_version": "1.0",
            "num_ports": 2,
            "datatype": "R",
            "frequency_unit": "Hz",
            "frequency_Hz": np.array([], dtype=np.float64),
        }

        for line in lines:
            stripped = line.strip()
            if not stripped.startswith("#"):
                break

            # Touchstone 2.x header: # F MHz/GHz S DB/R/A ...
            parts = stripped.split()
            if len(parts) < 1 or parts[0] != "#":
                continue

            if len(parts) >= 2 and parts[1].lower() == "touchstone":
                meta["format_version"] = parts[2] if len(parts) > 2 else "2.0"

            # Detect port count from .sNp in comment
            for p in parts:
                if p.startswith(".") and len(p) <= 4 and "s" in p.lower():
                    try:
                        meta["num_ports"] = int(p.split("s")[1])
                    except (IndexError, ValueError):
                        pass

            # Detect datatype
            for p in parts:
                if p.upper() in ("S", "Y", "Z", "H"):
                    meta["datatype"] = p
                    break

            # Frequency line
            if len(parts) >= 2 and parts[1].lower() == "hz":
                try:
                    f = float(parts[2])
                    meta["frequency_Hz"] = np.array([f], dtype=np.float64)
                    meta["frequency_unit"] = "Hz"
                except (IndexError, ValueError):
                    pass
            elif len(parts) >= 2 and parts[1].lower() == "mhz":
                try:
                    f = float(parts[2]) * 1e6
                    meta["frequency_Hz"] = np.array([f], dtype=np.float64)
                    meta["frequency_unit"] = "MHz"
                except (IndexError, ValueError):
                    pass
            elif len(parts) >= 2 and parts[1].lower() == "ghz":
                try:
                    f = float(parts[2]) * 1e9
                    meta["frequency_Hz"] = np.array([f], dtype=np.float64)
                    meta["frequency_unit"] = "GHz"
                except (IndexError, ValueError):
                    pass

        return meta

    def import_file(self, filename: str) -> dict:
        """Parse a Touchstone file and return structured data.

        Parameters
        ----------
        filename : str
            Path to the ``.sNp`` file.

        Returns
        -------
        dict
            Dictionary with keys:
                * ``frequency_Hz``  : np.ndarray of frequencies in Hz.
                * ``S_params``      : dict mapping ``(port_i, port_j)`` tuples
                                      to np.ndarray of complex S-parameters.
                * ``metadata``      : dict with format version, ports, datatype.
        """
        if not os.path.exists(filename):
            raise FileNotFoundError(f"Touchstone file not found: {filename}")

        with open(filename, "r") as fh:
            raw_lines = fh.readlines()

        # Strip trailing whitespace / newlines
        lines = [l.rstrip() for l in raw_lines]

        # Parse header
        metadata = self._parse_header(lines)
        self.num_ports = metadata["num_ports"]
        self.datatype = metadata["datatype"]

        # Determine how many data points (each row after the first data line)
        # For Touchstone 1.x the frequency is on the same line as the first data.

        # Find first non-comment line (first data line)
        data_start = None
        for i, line in enumerate(lines):
            if not line.strip().startswith("#"):
                data_start = i
                break

        if data_start is None:
            raise ValueError(f"File {filename} contains no data lines.")

        self.frequency_Hz = metadata["frequency_Hz"]

        # Build S_params dict
        S_params: Dict[tuple, np.ndarray] = {}
        freq_list: list[float] = []
        for p in range(self.num_ports):
            for q in range(self.num_ports):
                S_params[(p + 1, q + 1)] = np.array([], dtype=complex)

        # Parse data rows
        num_freq = 0
        for line in lines[data_start:]:
            parts = line.strip().split()
            if not parts:
                continue
            try:
                freq_val = float(parts[0])
            except (IndexError, ValueError):
                continue

            freq_list.append(freq_val)

            # Build complex values for each port pair
            offset = 1  # skip frequency column
            for p in range(self.num_ports):
                for q in range(self.num_ports):
                    re_str = parts[offset]
                    im_str = parts[offset + 1]
                    val = complex(float(re_str), float(im_str))
                    S_params[(p + 1, q + 1)] = np.append(
                        S_params[(p + 1, q + 1)], val
                    )
                    offset += 2

            num_freq += 1

        if self.frequency_Hz.size == 0:
            # Fallback: assume Hz from file content or default to parsed values
            self.frequency_Hz = np.array(freq_list, dtype=np.float64)

        return {
            "frequency_Hz": self.frequency_Hz[:num_freq] if num_freq else self.frequency_Hz,
            "S_params": S_params,
            "metadata": metadata,
        }


# ---------------------------------------------------------------------------
# HDF5 Exporter / Importer
# ---------------------------------------------------------------------------

try:
    import h5py  # type: ignore
except ImportError:
    h5py = None  # type: ignore  # noqa: F405


class HDF5Exporter:
    """Write field data and simulation results to an HDF5 file.

    Parameters
    ----------
    filename : str
        Output HDF5 file path (e.g. ``"results.h5"``).

    Example
    -------
    >>> exporter = HDF5Exporter("demo.h5")
    >>> exporter.save_fields(E_theta, E_phi, theta_deg, phi_deg)
    """

    def __init__(self, filename: str) -> None:
        if h5py is None:
            warnings.warn(
                "h5py is not installed. HDF5 functionality will be disabled."
            )
        self.filename = filename

    def save_fields(
        self,
        E_theta: np.ndarray,
        E_phi: np.ndarray,
        theta_deg: np.ndarray,
        phi_deg: np.ndarray,
        frequency_Hz: float = 1e9,
        S_params: Optional[np.ndarray] = None,
        currents: Optional[np.ndarray] = None,
    ) -> None:
        """Save field data and/or simulation results to HDF5.

        Creates groups::

            /fields/E_theta   (array)
            /fields/E_phi     (array)
            /metadata/frequency  (scalar or array)
            /results/S_params    (optional)
            /results/currents    (optional)

        Parameters
        ----------
        E_theta : np.ndarray
            Theta-component of the far-field.
        E_phi : np.ndarray
            Phi-component of the far-field.
        theta_deg : np.ndarray
            Polar angles in degrees.
        phi_deg : np.ndarray
            Azimuthal angles in degrees.
        frequency_Hz : float, optional
            Simulation frequency in Hz. Default 1e9.
        S_params : np.ndarray or None
            Optional S-parameter array.
        currents : np.ndarray or None
            Optional current distribution array.
        """
        if h5py is None:
            raise RuntimeError(
                "h5py is not installed. Install it via ``pip install h5py``."
            )

        with h5py.File(self.filename, "w") as hf:
            # Field data
            fields = hf.create_group("fields")
            fields.create_dataset("E_theta", data=E_theta)
            fields.create_dataset("E_phi", data=E_phi)

            # Metadata
            meta = hf.create_group("metadata")
            meta.create_dataset("frequency_Hz", data=frequency_Hz)
            meta.create_dataset("theta_deg", data=theta_deg)
            meta.create_dataset("phi_deg", data=phi_deg)

            # Optional results
            if S_params is not None:
                res = hf.create_group("results")
                res.create_dataset("S_params", data=S_params)

            if currents is not None:
                res = hf.require_group("results")
                res.create_dataset("currents", data=currents)


class HDF5Importer:
    """Read field data and simulation results from an HDF5 file.

    Parameters
    ----------
    filename : str
        Path to the HDF5 file (e.g. ``"results.h5"``).

    Example
    -------
    >>> importer = HDF5Importer("demo.h5")
    >>> fields = importer.load_fields()
    >>> metadata = importer.load_metadata()
    """

    def __init__(self, filename: str) -> None:
        if h5py is None:
            warnings.warn(
                "h5py is not installed. HDF5 functionality will be disabled."
            )
        self.filename = filename

    def load_fields(self) -> dict:
        """Load field data from the HDF5 file.

        Returns
        -------
        dict
            Dictionary with keys ``E_theta``, ``E_phi``, ``theta_deg``,
            ``phi_deg`` as NumPy arrays.
        """
        if h5py is None:
            raise RuntimeError(
                "h5py is not installed. Install it via ``pip install h5py``."
            )

        with h5py.File(self.filename, "r") as hf:
            fields = hf["fields"]
            return {
                "E_theta": np.asarray(fields["E_theta"]),
                "E_phi": np.asarray(fields["E_phi"]),
                "theta_deg": np.asarray(fields["theta_deg"]),
                "phi_deg": np.asarray(fields["phi_deg"]),
            }

    def load_metadata(self) -> dict:
        """Load the metadata group.

        Returns
        -------
        dict
            Dictionary with keys from ``/metadata`` (e.g. ``frequency_Hz``).
        """
        if h5py is None:
            raise RuntimeError(
                "h5py is not installed. Install it via ``pip install h5py``."
            )

        with h5py.File(self.filename, "r") as hf:
            meta = hf["metadata"]
            return {k: np.asarray(meta[k]) for k in meta.keys()}


# ---------------------------------------------------------------------------
# Example usage
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    # --- Touchstone Exporter / Importer demo ---
    print("=== Touchstone Demo ===")
    exporter = TouchstoneExporter(num_ports=2)
    freq = np.array([1e9, 2e9], dtype=np.float64)
    S = np.zeros((2, 2, 2), dtype=complex)
    S[0, 0, 0] = 0.1 + 0.2j
    S[0, 1, 0] = 0.05 + 0.03j
    S[0, 0, 1] = 0.05 - 0.03j
    S[0, 1, 1] = 0.15 + 0.1j
    exporter.export("demo.s2p", freq, S)

    importer = TouchstoneImporter()
    data = importer.import_file("demo.s2p")
    print(f"Frequency (Hz): {data['frequency_Hz']}")
    print(f"Metadata: {data['metadata']}")
    print(f"S11 at 1 GHz: {data['S_params'][(1, 1)][0]}")

    # --- HDF5 demo (if h5py available) ---
    print("\n=== HDF5 Demo ===")
    Nt, Np = 3, 4
    E_theta = np.random.rand(Nt, Np) + 1j * np.random.rand(Nt, Np)
    E_phi = np.random.rand(Nt, Np) + 1j * np.random.rand(Nt, Np)
    theta_deg = np.linspace(0, 180, Nt)
    phi_deg = np.linspace(0, 360, Np)

    h5e = HDF5Exporter("demo.h5")
    h5e.save_fields(E_theta, E_phi, theta_deg, phi_deg, frequency_Hz=2e9)

    h5i = HDF5Importer("demo.h5")
    fields = h5i.load_fields()
    meta = h5i.load_metadata()
    print(f"E_theta shape: {fields['E_theta'].shape}")
    print(f"Frequency: {meta['frequency_Hz']}")
